name: uplift_reconnect
description: Control Uplift standing desks that have the Uplift Connect BLE dongle installed.
publish_to: none

version: 1.2.0+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^11.0.0
  shared_preferences: ^2.5.5
  universal_ble: ^2.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DeskIcon
      fonts:
        - asset: fonts/DeskIcon.ttf
