// Regenerates assets/native_licenses.json, the licence page's record of the
// libraries the app ships natively. Flutter's own NOTICES asset only covers the
// Dart packages, so the Android libraries that Gradle resolves and the pods
// CocoaPods installs are collected here.
//
// Both platforms have to have been built at least once, so that Gradle's wrapper
// exists and CocoaPods has written its acknowledgements:
//
//   flutter build apk --debug
//   flutter build ios --debug --no-codesign
//   dart run tool/update_native_licenses.dart
//
// Run this after any dependency change. The README carries the short version.

import 'dart:convert';
import 'dart:io';

/// Written by the AboutLibraries Gradle plugin, which `android/app/build.gradle.kts`
/// applies for exactly this.
const _androidExport = 'build/app/generated/aboutLibraries/aboutlibraries.json';

/// Written by CocoaPods on every `pod install`, so it tracks the Podfile.
const _iosExport =
    'ios/Pods/Target Support Files/Pods-Runner/'
    'Pods-Runner-acknowledgements.markdown';

const _asset = 'assets/native_licenses.json';

Future<void> main() async {
  await _exportAndroidLicences();

  // Grouped by licence text, so the dozens of libraries sharing one licence
  // become a single entry listing all of their names.
  final byText = <String, List<String>>{};
  _add(byText, await _readAndroidLicences());
  _add(byText, await _readIosLicences());

  final entries = byText.entries.toList()
    ..sort((a, b) => a.value.first.compareTo(b.value.first));
  for (final entry in entries) {
    entry.value.sort();
  }

  final json = [
    for (final entry in entries) {'titles': entry.value, 'text': entry.key},
  ];
  await File(
    _asset,
  ).writeAsString('${const JsonEncoder.withIndent('  ').convert(json)}\n');

  final names = byText.values.fold(0, (sum, names) => sum + names.length);
  stdout.writeln(
    'Wrote $names libraries in ${entries.length} licences to $_asset',
  );
}

void _add(Map<String, List<String>> byText, Map<String, String> licences) {
  for (final entry in licences.entries) {
    byText.putIfAbsent(entry.value, () => []).add(entry.key);
  }
}

/// Asks Gradle to re-resolve the release classpath and describe its licences.
Future<void> _exportAndroidLicences() async {
  final result = await Process.run('./gradlew', [
    ':app:exportLibraryDefinitions',
  ], workingDirectory: 'android');
  if (result.exitCode != 0) {
    stderr.write(result.stdout);
    stderr.write(result.stderr);
    throw ProcessException(
      './gradlew',
      [':app:exportLibraryDefinitions'],
      'Run `flutter build apk --debug` first to create the Gradle wrapper.',
      result.exitCode,
    );
  }
}

Future<Map<String, String>> _readAndroidLicences() async {
  final export =
      jsonDecode(await File(_androidExport).readAsString())
          as Map<String, dynamic>;
  final texts = (export['licenses'] as Map<String, dynamic>).map(
    (id, licence) =>
        MapEntry(id, (licence as Map<String, dynamic>)['content'] as String),
  );

  return {
    for (final library in export['libraries'] as List<dynamic>)
      (library as Map<String, dynamic>)['uniqueId'] as String: _textFor(
        library,
        texts,
      ),
  }..removeWhere((_, text) => text.isEmpty);
}

String _textFor(Map<String, dynamic> library, Map<String, String> texts) {
  final ids = (library['licenses'] as List<dynamic>).cast<String>();
  if (ids.isEmpty) {
    // Only the Flutter engine artefacts land here: they are published without
    // licence metadata, and NOTICES already lists the engine as `flutter`.
    // Anything else needs attributing by hand rather than quietly going missing.
    final id = library['uniqueId'] as String;
    if (!id.startsWith('io.flutter:')) {
      throw StateError('$id declares no licence');
    }
    return '';
  }
  return ids.map((id) => texts[id]!).join('\n\n');
}

Future<Map<String, String>> _readIosLicences() async {
  final acknowledgements = File(_iosExport);
  if (!acknowledgements.existsSync()) {
    throw StateError(
      '${acknowledgements.path} is missing. '
      'Run `flutter build ios --debug --no-codesign` first.',
    );
  }

  final licences = <String, String>{};
  var pod = '';
  final body = StringBuffer();
  for (final line in (await acknowledgements.readAsString()).split('\n')) {
    if (line.startsWith('## ')) {
      if (pod.isNotEmpty) {
        licences[pod] = body.toString().trim();
      }
      pod = line.substring(3).trim();
      body.clear();
    } else if (pod.isNotEmpty && !line.startsWith('Generated by CocoaPods')) {
      body.writeln(line);
    }
  }
  if (pod.isNotEmpty) {
    licences[pod] = body.toString().trim();
  }
  return licences;
}
